version: "2"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - "/var/lib/grafana:/var/lib/grafana"
    environment: 
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
  alertmanager:
    image: prom/alertmanager:master
    container_name: alertmanager
    restart: always
    command:
      - "-config.file=/etc/alertmanager/alertmanager.yml"
    ports:
      - 9093:9093
    volumes:
      - "./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml"
  prometheus:
    image: prom/prometheus:master
    container_name: prometheus
    depends_on:
      - alertmanager
    restart: always
    command: 
      - "-config.file=/etc/prometheus/prometheus.yml"
      - "-storage.local.path=/var/lib/prometheus/metrics"
      - "-storage.local.retention=360h"
      - "-alertmanager.url=http://172.17.0.1:9093"
      - "-web.console.libraries=/usr/share/prometheus/console_libraries"
      - "-web.console.templates=/usr/share/prometheus/consoles"
      - "-web.enable-remote-shutdown=false"
    ports:
      - 9090:9090
    volumes:
      - "./config/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "/var/lib/prometheus/metrics:/var/lib/prometheus/metrics"
  weather_exporter:
    image: celliott/weather_exporter:latest
    container_name: weather_exporter
    ports:
      - ${ENDPOINT_PORT}:${ENDPOINT_PORT}
    environment:
      - DARK_SKY_API_KEY=${DARK_SKY_API_KEY}
      - SCRAPE_INTERVAL=${SCRAPE_INTERVAL}
      - CITIES=${CITIES}
  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    restart: always
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - -collector.procfs=/host/proc
      - -collector.sysfs=/host/sys
  collectd_exporter:
    image: prom/collectd-exporter:master
    container_name: collectd_exporter
    ports:
      - 9103:9103
