# Sample config for Prometheus.

global:
  scrape_interval:     30s
  scrape_timeout:      30s
  evaluation_interval: 30s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'prometheus'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:

  - job_name: monitoring
    static_configs:

      # prometheus
      - targets:
        - 'node_exporter:9100'
        labels:
          alias: 'telemetry-node'
          
      - targets:
        - 'cadvisor:8080'
        labels:
          alias: 'telemetry-containers'
          
  - job_name: weather_exporter
    metrics_path: /
    static_configs:

      - targets:
        - 'weather_exporter:9265'
        labels:
          alias: 'weather-exporter'

  - job_name: collectd_exporter
    static_configs:
      - targets:
        - 'collectd_exporter:9103'
        labels:
          alias: 'collectd-exporter'
